lib/dsa_web/router.ex
defmodule DsaWeb.Router do
  use DsaWeb, :router

  import DsaWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {DsaWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: DsaWeb.Telemetry, ecto_repos: [Dsa.Repo]
    end
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  # Public Routes
  scope "/", DsaWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/talente", SkillController, :index
    get "/talente/:slug", SkillController, :show
  end

  ## Authentication routes

  scope "/", DsaWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/registrierung", UserRegistrationController, :new
    post "/registrierung", UserRegistrationController, :create
    get "/login", UserSessionController, :new
    post "/login", UserSessionController, :create
    get "/passwort_zuruecksetzen", UserResetPasswordController, :new
    post "/passwort_zuruecksetzen", UserResetPasswordController, :create
    get "/passwort_zuruecksetzen/:token", UserResetPasswordController, :edit
    put "/passwort_zuruecksetzen/:token", UserResetPasswordController, :update
  end

  scope "/", DsaWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/einstellungen", UserSettingsController, :edit
    put "/einstellungen", UserSettingsController, :update
    get "/einstellungen/confirm_email/:token", UserSettingsController, :confirm_email

    # heldenverwaltung
    get "/helden", CharacterController, :index
    post "/helden", CharacterController, :create
    put "/helden/:id/aktivieren", CharacterController, :activate
    put "/helden/:id/deaktivieren", CharacterController, :deactivate
    put "/helden/:id/auswaehlen", CharacterController, :select
    delete "/helden/:id", CharacterController, :delete
  end

  scope "/", DsaWeb do
    pipe_through [:browser]

    delete "/ausloggen", UserSessionController, :delete
    get "/account_bestaetigen", UserConfirmationController, :new
    post "/account_bestaetigen", UserConfirmationController, :create
    get "/account_bestaetigen/:token", UserConfirmationController, :confirm
  end

  scope "/verwalten", DsaWeb do
    pipe_through [:browser, :require_authenticated_user, :require_admin_user]

    get "/suche_synconisieren", ManageController, :sync_search
  end

  # # Public Routes
  # scope "/", DsaWeb do
  #   pipe_through :browser

  #   resources "/character", CharacterController, only: [:show]

  #   # Public Data Routes
  #   resources "/groups", GroupController, only: [:index]
  #   resources "/skills", SkillController, only: [:index]
  #   resources "/spells", SpellController, only: [:index]
  #   resources "/blessings", BlessingController, only: [:index]


  #   resources "/dice_tables", DiceTableController do
  #      resources "/entries", DiceTableEntryController
  #      post "/dice_table_roll", EventController, :dice_table_roll
  #   end

  #   # user registration
  #   # get "/user/confirm/:token", UserController, :confirm

  #   # reset password logic
  #   # get "/user/reset", UserController, :reset
  #   # post "/user/reset", UserController, :send_reset_link
  #   # get "/user/reset/:token", UserController, :reset_password
  #   # put "/user/reset/:token", UserController, :update_password
  # end

  # # Private Routes
  # scope "/", DsaWeb do
  #   pipe_through [:browser, :require_authenticated_user]

  #   put "/character/:id/activate", CharacterController, :activate
  #   put "/character/:id/toggle_visible", CharacterController, :toggle_visible

  #   resources "/characters", CharacterController, except: [:show] do

  #     # Combat Sets
  #     resources "/combat_sets", CombatSetController, except: [:show]

  #     # Character Skills
  #     resources "/skills", CharacterSkillController, only: [:index], as: :skill
  #     get "/skills/edit", CharacterSkillController, :edit_all, as: :skill
  #     put "/skills/update", CharacterSkillController, :update_all, as: :skill
  #     put "/skills/add", CharacterSkillController, :add_all, as: :skill
  #     delete "/skills/remove", CharacterSkillController, :remove_all, as: :skill

  #     # Character Spells
  #     resources "/spells", CharacterSpellController, only: [:index], as: :spell
  #     get "/spells/edit", CharacterSpellController, :edit_all, as: :spell
  #     put "/spells/update", CharacterSpellController, :update_all, as: :spell
  #     put "/spells/add", CharacterSpellController, :add_all, as: :spell
  #     delete "/spells/remove", CharacterSpellController, :remove_all, as: :spell

  #     # Character Blessings
  #     resources "/blessings", CharacterBlessingController, only: [:index], as: :blessing
  #     get "/blessings/edit", CharacterBlessingController, :edit_all, as: :blessing
  #     put "/blessings/update", CharacterBlessingController, :update_all, as: :blessing
  #     put "/blessings/add", CharacterBlessingController, :add_all, as: :blessing
  #     delete "/blessings/remove", CharacterBlessingController, :remove_all, as: :blessing
  #   end

  #   # Event Routes
  #   post "/characters/:character_id/skill_roll", EventController, :skill_roll
  #   post "/characters/:character_id/spell_roll", EventController, :spell_roll
  #   post "/characters/:character_id/blessing_roll", EventController, :blessing_roll

  #   # resources "/user", UserController, only: [:delete, :edit, :update]

  #   # Groups
  #   put "/groups/join/:id", GroupController, :join
  #   delete "/groups/leave", GroupController, :leave
  #   resources "/groups", GroupController, except: [:index, :update]
  # end

  # # Admin Routes
  # scope "/", DsaWeb do
  #   pipe_through [:browser, :require_authenticated_user, :admin]

  #   resources "/skills", SkillController, except: [:index, :show]
  # end

  # ## Authentication routes

  # scope "/", DsaWeb do
  #   pipe_through [:browser, :redirect_if_user_is_authenticated]

  #   get "/login", UserSessionController, :new
  #   post "/login", UserSessionController, :create
  #   get "/register", UserRegistrationController, :new
  #   post "/register", UserRegistrationController, :create

  #   get "/users/reset_password", UserResetPasswordController, :new
  #   post "/users/reset_password", UserResetPasswordController, :create
  #   get "/users/reset_password/:token", UserResetPasswordController, :edit
  #   put "/users/reset_password/:token", UserResetPasswordController, :update
  # end

  # scope "/", DsaWeb do
  #   pipe_through [:browser, :require_authenticated_user]

  #   get "/users/settings", UserSettingsController, :edit
  #   put "/users/settings", UserSettingsController, :update
  #   get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

  #   delete "/users/delete", UserSettingsController, :delete
  # end

  # # Account Management

  # scope "/accounts", DsaWeb do
  #   pipe_through [:browser]

  #   delete "/logout", UserSessionController, :delete
  #   get "/confirm", UserConfirmationController, :new
  #   post "/confirm", UserConfirmationController, :create
  #   get "/confirm/:token", UserConfirmationController, :confirm
  # end

  # scope "/accounts", DsaWeb do
  #   pipe_through [:browser, :require_authenticated_user]

  #   get "/change_password", UserChangePasswordController, :edit
  #   post "/change_password", UserChangePasswordController, :update
  # end
end

lib/dsa_web/views/layout_view.ex
defmodule DsaWeb.LayoutView do
  use DsaWeb, :view

  import Phoenix.Controller, only: [get_flash: 1]
  import DsaWeb.AccountTranslations

  def title, do: gettext("DSA Tool")
  def description, do: gettext("Ein Heldenbogen-, Würfel- und Gruppentool für DSA, Das Schwarze Auge")

  @doc """
  Returns name and profession of active character or default entries, if non is selected.

  ## Examples
      iex> active_character_info(current_user)
      {"Ethric", "Elementarmagier"}

      iex> active_character_info(user_without_active_character)
      {"Kein Held ausgewählt", "Held erstellen"}
  """
  def active_character_info(current_user) do
    if is_nil(current_user.active_character_id) do
      {gettext("Held erstellen"), gettext("Kein Held ausgewählt")}
    else
      character = Enum.find(current_user.characters, &(&1.id == current_user.active_character_id))
      {character.name, character.profession}
    end
  end

  # defp active_character_name(%User{} = current_user) do
  #   if is_nil(current_user.active_character_id) do
  #     gettext("No active character")
  #   else
  #     Enum.find(@current_user.characters, & &1.id == @current_user.active_character_id).name
  #   end
  # end

  def alert_icon(type) do
    case type do
      :error -> "x-circle-solid"
      "error" -> "x-circle-solid"
      "info" -> "information-circle-solid"
      "success" -> "check-circle-solid"
    end
  end

  defp menu_item(conn, name, [to: path, icon: iname]) do
    active_class = if path == Path.join(["/" | conn.path_info]), do: " active"

    link [content_tag(:div, icon(iname)), content_tag(:span, name)],
      to: path,
      class: "menu-item#{active_class}"
  end

  # size is in rem (by default 4 pixel)
  defp gravatar_url(email, size \\ 10) when is_binary(email) do
    email = email |> String.trim() |> String.downcase(:ascii)
    hash = :crypto.hash(:md5, email) |> Base.encode16(case: :lower)
    "https://www.gravatar.com/avatar/#{hash}?s=#{size*4}&d=mp"
  end

  defp active_class(conn, path) do
    if path == Path.join(["/" | conn.path_info]), do: "active", else: nil
  end

  def link(conn, text, opts) do
    class = [opts[:class], active_class(conn, opts[:to])] |> Enum.filter(& &1) |> Enum.join(" ")
    link text, Keyword.put(opts, :class, class)
  end

  def link(:auth, conn, text, opts) do
    if auth?(conn), do: link(conn, text, opts), else: nil
  end
end

lib/dsa_web/templates/layout/alert.html.eex
<div class="alert <%= @type %>"
  x-data='{ dismissed: false }'
  x-show='!dismissed'
  x-transition:leave="transition-opacity ease-linear duration-300"
  x-transition:leave-start="opacity-100"
  x-transition:leave-end="opacity-0">
  <div class="flex">
    <div class="flex-shrink-0"><%= icon(alert_icon(@type)) %></div>
    <div class="ml-3"><p><%= @message %></p></div>
    <div class="ml-auto pl-3">
      <div class="-mx-1.5 -my-1.5">
        <button type='button' @click='dismissed=!dismissed'>
          <span class="sr-only"><%= gettext("ausblenden") %></span>
          <%= icon("x") %>
        </button>
      </div>
    </div>
  </div>
</div>

lib/dsa_web/templates/layout/app.html.eex
<%# Page Wrapper %>
<div class='page-wrapper' x-data='{open:false}' x-init='elms = document.querySelector(".desktop-wrapper nav"); '>
  <%# SimpleScrollbar.initEl(elms); %>
  <%# Mobile Sidebar Wrapper %>
  <div class="mobile-wrapper" role="dialog" aria-modal="true" x-show='open===true'>
    <%# Mobile Backdrop %>
    <div class="mobile-backdrop" aria-hidden="true"
      @click='open=false'
      x-show='open===true'
      x-transition:enter='transition-opacity ease-linear duration-300'
      x-transition:enter-start='opacity-0'
      x-transition:enter-end='opacity-100'
      x-transition:leave='transition-opacity ease-linear duration-300'
      x-transition:leave-start='opacity-100'
      x-transition:leave-end='opacity-0'></div>
    <%# Mobile Sidebar %>
    <div class="mobile-sidebar-wrapper"
      x-show='open===true'
      x-transition:enter='transition ease-in-out duration-300 transform'
      x-transition:enter-start='-translate-x-full'
      x-transition:enter-end='translate-x-0'
      x-transition:leave='transition ease-in-out duration-300 transform'
      x-transition:leave-start='translate-x-0'
      x-transition:leave-end='-translate-x-full'>
      <%# Mobile Close Button %>
      <div class="mobile-close-button-wrapper"
        x-show='open===true'
        x-transition:enter='ease-in-out duration-300'
        x-transition:enter-start='opacity-0'
        x-transition:enter-end='opacity-100'
        x-transition:leave='ease-in-out duration-300'
        x-transition:leave-start='opacity-100'
        x-transition:leave-end='opacity-0'>
        <button class="mobile-close-button" @click='open=false'>
          <span class="sr-only"><%= gettext("Schließe seitliches Menü") %></span>
          <%# Heroicon name: outline/x %>
          <%= icon("x", "m-2 h-8 w-8 text-white") %>
        </button>
      </div>
      <%# Mobile Sidebar Content %>
      <%= render DsaWeb.LayoutView, "sidebar.html", conn: @conn, current_user: @current_user %>

      <div class="mobile-shrink"></div>
    </div>
  </div>
  <%# Static Sidebar for Desktop %>
  <div class="desktop-wrapper">
    <div class="flex flex-col w-64">
      <%# Sidebar Component %>
      <div class="desktop-sidebar-wrapper">
        <%# Desktop Sidebar Content %>
        <%= render DsaWeb.LayoutView, "sidebar.html", conn: @conn, current_user: @current_user %>
      </div>
    </div>
  </div>
  <%# Content Area %>
  <div class="content-area">
    <%# Top Bar %>
    <div class="top-bar">
      <div>
        <button class="menu-button" @click='open=true'>
          <span class="sr-only"><%= gettext("Öffne seitliches Menü") %></span>
          <%= icon("menu", "m-2 h-8 w-8") %>
        </button>
        <%# Search Button and Modal %>
        <%= render DsaWeb.LayoutView, "search.html", conn: @conn %>
        <%# User Menu / Login %>
        <%= render DsaWeb.LayoutView, "user_menu.html", conn: @conn, user: @current_user %>
      </div>
    </div>
    <main>
      <div>
        <%# Flash Messages %>
        <%= for {type, message} <- get_flash(@conn) do %>
          <%= render DsaWeb.LayoutView, "alert.html", type: type, message: message %>
        <% end %>
        <%# Page Content %>
        <div><%= @inner_content %></div>
      </div>
    </main>
  </div>
</div>

lib/dsa_web/templates/layout/character_selection.html.eex
<%= if @current_user do %>
  <%= if Enum.count(@current_user.characters) >= 2 do %>
    <div x-data='{ open: false }'>
      <button type='button' class="relative h-20 px-6 flex items-center justify-between rounded-none border-0 font-normal text-inherit text-left focus:outline-none focus:ring-0 bg-gray-700 group w-full hover:bg-gray-600" aria-expanded="false" aria-haspopup="true" @click='open=true'>
        <span class="sr-only"><%= gettext("Öffne Heldenauswahl") %></span>
        <div class="flex-grow overflow-hidden">
          <div class="text-gray-100 group-hover:text-white truncate text-lg"><%= @current_user.active_character.name %></div>
          <div class="truncate">
            <span class="text-gray-300 group-hover:text-gray-100"><%= @current_user.active_character.profession %></span>
          </div>
        </div>
        <%= icon("chevron-down-solid", "h-6 w-6 text-gray-300 group-hover:text-gray-100") %>
      </button>

      <div class="origin-top-right absolute right-0 mt-2 mr-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none z-10" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1"
        @click.away="open=false"
        x-show='open===true'
        x-transition:enter='transition ease-out duration-100'
        x-transition:enter-start='transform opacity-0 scale-95'
        x-transition:enter-end='transform opacity-100 scale-100'
        x-transition:leave='transition ease-in duration-75'
        x-transition:leave-start='transform opacity-100 scale-100'
        x-transition:leave-end='transform opacity-0 scale-95'>
        <!-- Active: "bg-gray-100", Not Active: "" -->
        <%= link gettext("Heldenübersicht"), to: Routes.character_path(@conn, :index), class: "block px-4 py-2 text-sm text-gray-700", role: "menuitem", tabindex: -1 %>

        <%= for character <- @current_user.characters do %>

          <%= link character.name, to: Routes.character_path(@conn, :select, character.id), class: "block px-4 py-2 text-sm text-gray-700", method: :put, role: "menuitem", tabindex: -1 %>

        <% end %>
      </div>
    </div>
  <% else %>
    <%= link to: Routes.character_path(@conn, :index), class: "character-selection" do %>
      <%= if @current_user.active_character do %>
        <span class='text-white text-lg px-2'><%= @current_user.active_character.name %></span>
        <span class='px-2'><%= @current_user.active_character.profession %></span>
      <% else %>
        <span class='text-white text-lg px-2'><%= gettext("Held erstellen") %></span>
        <span class='px-2'><%= gettext("Heldenübersicht") %></span>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <div class='character-selection'>
    <%= link dgettext("account", "Account erstellen"), to: Routes.user_registration_path(@conn, :new), class: "text-white text-lg px-2 rounded-lg hover:bg-gray-800" %>
    <%= link dgettext("account", "oder melde dich an"), to: Routes.user_session_path(@conn, :new), class: "px-2 rounded-lg hover:bg-gray-800" %>
  </div>
<% end %>

lib/dsa_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=0.9, maximum-scale=0.9, user-scalable=no"/>
    <meta name="author" content="Alexander Fuchsberger">
    <meta name="description" content="<%= gettext("Ein Heldenbogen-, Würfel- und Gruppentool für DSA, Das Schwarze Auge") %>">
    <meta name="environment" content="<%= Application.get_env(:dsa, :environment) %>">
    <%= csrf_meta_tag() %>
    <title><%= gettext("DSA Tool") %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <%= @inner_content %>
  </body>
</html>

lib/dsa_web/templates/layout/search.html.eex
<div class='flex-grow'
  x-data='{ search: false, query: "", selected:null, results: [] }'
  x-init='window.addEventListener("keydown", e => {
      if((e.ctrlKey || e.metaKey)&&(e.keyCode == 71)){
        e.preventDefault();
        search=true;
        $nextTick(() => { document.getElementById("search_query").focus() });
        return false
      }
      if(search && e.keyCode == 27){
        e.preventDefault();
        search=false;
        return false;
      }
    });
    $watch("query", query => {
      if(query.length < 3) results = [];
      else searchIndex.search(query, { attributesToSnippet: ["name", "description", "list_entries" ], hitsPerPage: 5 }).then(search_results => {results = search_results.hits})
    })'>
  <button class='w-full flex items-center group text-gray-400 focus:outline-none border-0 hover:bg-white focus:ring-0'
    @click='search=true;$nextTick(() => { document.getElementById("search_query").focus() });' >
    <!-- Heroicon name: solid/search -->
    <%= icon("search-solid", "m-2 h-8 w-8 group-hover:text-gray-600") %>
    <span class='flex-grow truncate group-hover:text-gray-600'>
      <%= gettext("Search for anything...") %>
    </span>
    <span style="opacity: 1;" class="hidden sm:block key-combo">
      <span class="sr-only"><%= gettext("Drücke") %> </span>
      <kbd class="font-sans">
        <abbr title="Control" class="no-underline" x-show='navigator.platform !== "MacIntel" && navigator.platform !== "MacPPC"'><%= gettext("Strg") %></abbr>
        <abbr title="Control" class="no-underline" x-show='navigator.platform === "MacIntel" || navigator.platform === "MacPPC"'><%= gettext("⌘") %></abbr>
      </kbd>
      <span class="sr-only"> <%= gettext("und") %> </span>
      <kbd class="font-sans">G</kbd>
      <span class="sr-only"> <%= gettext("um zu suchen") %></span>
  </button>
  <%# Search Modal %>
  <div id='search-modal' class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true" x-show='search' style='display:none;'>
    <div class="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
      <%# Background Overlay %>
      <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"
        @click='search = false'
        x-show='search'
        x-transition:enter='ease-out duration-300'
        x-transition:enter-start='opacity-0'
        x-transition:enter-end='opacity-100'
        x-transition:leave='ease-in duration-200'
        x-transition:leave-start='opacity-100'
        x-transition:leave-end='opacity-0'></div>

      <!-- This element is to trick the browser into centering the modal contents. -->
      <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

      <%# Modal Panel %>
      <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full"
        x-show='search'
        x-transition:enter='ease-out duration-300'
        x-transition:enter-start='opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95'
        x-transition:enter-end='opacity-100 translate-y-0 sm:scale-100'
        x-transition:leave='ease-in duration-200'
        x-transition:leave-start='opacity-100 translate-y-0 sm:scale-100'
        x-transition:leave-end='opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95'>

        <%# Search Box Header %>
        <header class='px-4 py-2 sm:px-6 border-b'>
          <%= form_for :search, "#", [class: "flex items-center", novalidate: true, "x-on:submit.prevent": true], fn f -> %>
            <%= label f, :query do %>
              <%= icon("search-solid", "h-8 w-8 my-2 mr-2") %>
            <% end %>
            <%= label f, :query, class: "sr-only", do: gettext("Suche") %>

            <%= search_input f, :query, value: "", "x-model.debounce.300": "query", placeholder: gettext("search DSA Tool") %>

            <%# Close Button %>
            <button type="button" class="key-combo" @click='search=false'><kbd class="font-sans"><%= gettext("esc") %></kbd></button>
          <% end %>
        </header>

        <%# Search Results Section %>
        <ul role='listbox' class="px-4 sm:px-6 py-3 space-y-2">
          <template x-for="item in results" :key="item">
            <li class='search-hit' role='option' @mouseenter="if(selected !== item.objectID) selected = item.objectID;" :aria-selected='selected === item.objectID ? "true" : "false"'>
              <a x-bind:href="item.path" class='flex items-center'>
                <div class="flex-grow flex flex-col">
                  <div class='overflow-y-hidden'>
                    <strong x-html='item._snippetResult.name.value' class='text-black'></strong>
                    <span x-text='"(" + item.type + ")"' class='ml-2 italic'></span>
                  </div>
                  <small x-html='item._snippetResult.description.value' class='text-justify truncate'></small>
                  <small x-show='item.list_entries.length > 0' class='truncate'>
                    <strong x-text='item.list_name'></strong>
                    <template x-for="entry in item._snippetResult.list_entries" :key="entry">
                      <span x-html='entry.value' class='rounded-full ml-0.5 px-1 bg-gray-300 text-black'></span>
                    </template>
                  </small>
                </div>
                <%= icon("select", "pl-3 w-8 h-8") %>
              </a>
            </li>
          </template>
        </ul>
      </div>
    </div>
  </div>
</div>

lib/dsa_web/templates/layout/sidebar.html.eex
<div class="sidebar">
  <header class="flex-shrink-0 flex items-center justify-center h-12">
    <%= icon("eye-solid", "h-10 w-10 text-indigo-500") %>
    <div class='pl-3 text-gray-200 text-3xl font-bold tracking-tighter'><%= gettext("DSA Tool") %></div>
  </header>

  <%= render "character_selection.html", conn: @conn, current_user: @current_user %>

  <nav>
    <%= menu_item(@conn, gettext("Tool Info"), to: Routes.page_path(@conn, :index), icon: "home") %>
    <%= menu_item(@conn, gettext("Talente"), to: Routes.skill_path(@conn, :index), icon: "cog-solid") %>
  </nav>

  <div class='flex-shrink-0 bg-gray-700'>
    TODO: Log Entries
  </div>
</div>

lib/dsa_web/templates/layout/user_menu.html.eex
<%= if @user do %>
  <div class="ml-2 relative" x-data='{ open: false }'>
    <button type="button" class="flex items-center text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-1 focus:ring-indigo-500 p-1" id="user-menu-button" aria-expanded="false" aria-haspopup="true" @click='open=true'>
      <span class="sr-only"><%= dgettext("account", "Öffne Benutzermenu") %></span>
      <img class="h-10 w-10 rounded-full" src="<%= gravatar_url(@user.email) %>" alt="">
    </button>
    <div class="origin-top-right absolute right-0 mt-2 mr-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none z-10" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1"
      @click.away="open=false"
      x-show='open===true'
      x-transition:enter='transition ease-out duration-100'
      x-transition:enter-start='transform opacity-0 scale-95'
      x-transition:enter-end='transform opacity-100 scale-100'
      x-transition:leave='transition ease-in duration-75'
      x-transition:leave-start='transform opacity-100 scale-100'
      x-transition:leave-end='transform opacity-0 scale-95'>
      <!-- Active: "bg-gray-100", Not Active: "" -->
      <%= link t(:settings), to: Routes.user_settings_path(@conn, :edit), class: "block px-4 py-2 text-sm text-gray-700", role: "menuitem", tabindex: -1 %>

      <%= link t(:sign_out), to: Routes.user_session_path(@conn, :delete), class: "block px-4 py-2 text-sm text-gray-700", method: :delete, role: "menuitem", tabindex: -1 %>
    </div>
  </div>
<% else %>
  <div class="ml-2 relative">
    <%= link to: Routes.user_session_path(@conn, :new),
      class: "focus:outline-none hover:text-gray-600", title: t(:sign_in) do %>
      <span class="sr-only"><%= gettext("zur Anmeldung") %></span>
      <!-- Heroicon name: outline/login -->
      <%= icon("login", "m-2 h-8 w-8") %>
    <% end %>
  </div>
<% end %>